---
name: Default Workflow
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      checkov:
        description: Deprecated. Use checkov.yml directly when needed.
        default: true
        required: false
        type: boolean
      merge-checks-timeout:
        description: Seconds to wait for other checks to complete.
        default: 600
        required: false
        type: number

permissions:
  checks: read
  statuses: read
  contents: read

jobs:
  merge-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@09af7a82c1666d0e64d2bd8c01797a0bcfd3bb5d # v1
        with:
          token: ${{ github.token }}
          ignored: "merge-checks, check / merge-checks, policy-bot: main"
          timeout: ${{ inputs.merge-checks-timeout }}
          interval: 5
